server:
  port: 8401

eureka:
  client:
    service-url:
      defaultZone : http://${security.user.name}:${security.user.password}@localhost:8761/eureka/   #连接到服务注册中心的地址，如果服务注册中心开启了权限需要设置 http://username:password@ip:port/eureka/格式
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

    # 客户端与服务器断心跳的时间间隔，默认为 30秒
    lease-renewal-interval-in-seconds: 3
    # 租约到期时间，此值不可过小，开发环境小点没有事，默认为 90秒
    lease-expiration-duration-in-seconds: 9

security:
  user:
    name: root
    password: admin
spring:
  application:
    name: spring-boot-admin-server
  boot:
    admin:
      context-path: /admin
  mail:
    default-encoding: UTF-8
    host: smtp.exmail.qq.com
    password: 邮箱用户名
    username: 邮箱密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  security:
    enabled: false

logging:
  path: logs

info:
  app:
    name: "spring-boot-admin-server-8401"
    description: "spring-boot-admin-server-8401程序"
    version: "0.0.1"