server:
  port: 8762


eureka:
  client:
    service-url:
      defaultZone : http://${security.user.name}:${security.user.password}@localhost:8761/eureka/   #连接到服务注册中心的地址，如果服务注册中心开启了权限需要设置 http://username:password@ip:port/eureka/格式
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

    # 客户端与服务器断心跳的时间间隔，默认为 30秒
    lease-renewal-interval-in-seconds: 3
    # 租约到期时间，此值不可过小，开发环境小点没有事，默认为 90秒
    lease-expiration-duration-in-seconds: 9

security:
  user:
    name: root
    password: admin
spring:
  application:
    name: eureka-client


info:
  app:
    name: "eureka-client"
    description: "eureka-client程序"
    version: "0.0.1"